### ISSUE TITLE
Pass the test-tidy

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#218]
Please run following command for checking
```bash
./mach test-tidy --all
```

# 2016-08-30
https://travis-ci.org/Mozilla-TWQA/Hasal/builds/156168767
## TODO
- [x] ./lib/browser/firefox.py:30: no newline at EOF
- [x] ./lib/common/imageTool.py:295: no newline at EOF
- [x] ./lib/common/outlier.py:18: trailing whitespace
- [x] ./lib/common/outlier.py:21: trailing whitespace
- [x] ./lib/profiler/traceloggerProfiler.py:49: no newline at EOF
- [x] ./lib/sikuli/common.sikuli/common.py:2: tab on line
- [x] ./tests/pilot/bbc/test_chrome_editor_pick.sikuli/test_chrome_editor_pick.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_headline.sikuli/test_chrome_headline.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_headline.sikuli/test_chrome_headline.py:10: no newline at EOF
- [x] ./tests/pilot/bbc/test_chrome_homepage.sikuli/test_chrome_homepage.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_homepage_pagedown.sikuli/test_chrome_homepage_pagedown.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_pictures.sikuli/test_chrome_pictures.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_search.sikuli/test_chrome_search.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_search.sikuli/test_chrome_search.py:15: no newline at EOF
- [x] ./tests/pilot/bbc/test_chrome_video.sikuli/test_chrome_video.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_video.sikuli/test_chrome_video.py:14: no newline at EOF
- [x] ./tests/pilot/bbc/test_chrome_weather.sikuli/test_chrome_weather.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_chrome_weather.sikuli/test_chrome_weather.py:5: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_editor_pick.sikuli/test_firefox_editor_pick.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_editor_pick.sikuli/test_firefox_editor_pick.py:5: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_headline.sikuli/test_firefox_headline.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_homepage.sikuli/test_firefox_homepage.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_homepage.sikuli/test_firefox_homepage.py:5: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_homepage_pagedown.sikuli/test_firefox_homepage_pagedown.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_homepage_pagedown.sikuli/test_firefox_homepage_pagedown.py:10: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_pictures.sikuli/test_firefox_pictures.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_pictures.sikuli/test_firefox_pictures.py:5: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_search.sikuli/test_firefox_search.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_search.sikuli/test_firefox_search.py:15: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_video.sikuli/test_firefox_video.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_video.sikuli/test_firefox_video.py:14: no newline at EOF
- [x] ./tests/pilot/bbc/test_firefox_weather.sikuli/test_firefox_weather.py:0: the file name should starts with 'test_$BROWSER_bbc_'
- [x] ./tests/pilot/bbc/test_firefox_weather.sikuli/test_firefox_weather.py:5: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_enlarge_image_1.sikuli/test_chrome_facebook_enlarge_image_1.py:7: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_enlarge_video_1.sikuli/test_chrome_facebook_enlarge_video_1.py:8: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_load_bluebar.sikuli/test_chrome_facebook_load_bluebar.py:5: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_load_homepage.sikuli/test_chrome_facebook_load_homepage.py:3: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_load_messages.sikuli/test_chrome_facebook_load_messages.py:6: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_mouse_scroll_homepage.sikuli/test_chrome_facebook_mouse_scroll_homepage.py:6: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_post_delete.sikuli/test_chrome_facebook_post_delete.py:11: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_post_link.sikuli/test_chrome_facebook_post_link.py:9: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_post_share.sikuli/test_chrome_facebook_post_share.py:8: no newline at EOF
- [x] ./tests/pilot/facebook/test_chrome_facebook_see_more_text.sikuli/test_chrome_facebook_see_more_text.py:8: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_enlarge_image_1.sikuli/test_firefox_facebook_enlarge_image_1.py:7: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_enlarge_video_1.sikuli/test_firefox_facebook_enlarge_video_1.py:8: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_load_bluebar.sikuli/test_firefox_facebook_load_bluebar.py:5: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_load_homepage.sikuli/test_firefox_facebook_load_homepage.py:3: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_load_messages.sikuli/test_firefox_facebook_load_messages.py:6: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_mouse_scroll_homepage.sikuli/test_firefox_facebook_mouse_scroll_homepage.py:6: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_post_delete.sikuli/test_firefox_facebook_post_delete.py:11: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_post_link.sikuli/test_firefox_facebook_post_link.py:10: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_post_share.sikuli/test_firefox_facebook_post_share.py:8: no newline at EOF
- [x] ./tests/pilot/facebook/test_firefox_facebook_see_more_text.sikuli/test_firefox_facebook_see_more_text.py:8: no newline at EOF
- [x] ./tests/pilot/gmail/test_chrome_gmail_view_images.sikuli/test_chrome_gmail_view_images.py:23: no newline at EOF
- [x] ./tests/pilot/gmail/test_firefox_gmail_launch.sikuli/test_firefox_gmail_launch.py:9: no newline at EOF
- [x] ./tests/pilot/gmail/test_firefox_gmail_view_images.sikuli/test_firefox_gmail_view_images.py:23: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_create_copypaste_txt_1.py:11: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_load_file.py:0: the file name should starts with 'test_$BROWSER_gdoc_'
- [x] ./tests/regression/gdoc/test_firefox_load_file.py:0: the file name should starts with 'test_$BROWSER_gdoc_'
- [x] ./tests/regression/gdoc/test_chrome_gdoc_create_copypaste_image_1.sikuli/test_chrome_gdoc_create_copypaste_image_1.py:26: trailing whitespace
- [x] ./tests/regression/gdoc/test_chrome_gdoc_create_copypaste_table_1.sikuli/test_chrome_gdoc_create_copypaste_table_1.py:24: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_create_copypaste_txt_1.sikuli/test_chrome_gdoc_create_copypaste_txt_1.py:38: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_create_cursormove_50.sikuli/test_chrome_gdoc_create_cursormove_50.py:34: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_delete_basic_table_1.sikuli/test_chrome_gdoc_delete_basic_table_1.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_delete_basic_txt_1.sikuli/test_chrome_gdoc_delete_basic_txt_1.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:19: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:20: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:21: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:22: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:23: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:24: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:25: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:26: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:27: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:28: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:30: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:31: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:32: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:33: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:34: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:35: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:36: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:37: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:39: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:40: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:41: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:42: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:43: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:44: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:45: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:46: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:47: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:48: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:50: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:51: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:52: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:53: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:54: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:55: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:56: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:65: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_format10.sikuli/test_chrome_gdoc_format10.py:66: tab on line
- [x] ./tests/regression/gdoc/test_chrome_gdoc_read_basic_image_1.sikuli/test_chrome_gdoc_read_basic_image_1.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_read_basic_table_1.sikuli/test_chrome_gdoc_read_basic_table_1.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_read_basic_table_1_sampleobj.sikuli/test_chrome_gdoc_read_basic_table_1_sampleobj.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_read_cursormove_3.sikuli/test_chrome_gdoc_read_cursormove_3.py:18: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_gdoc_update_replace_3.sikuli/test_chrome_gdoc_update_replace_3.py:23: trailing whitespace
- [x] ./tests/regression/gdoc/test_chrome_gdoc_update_undoredo_100.sikuli/test_chrome_gdoc_update_undoredo_100.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_chrome_load_file.sikuli/test_chrome_load_file.py:0: the file name should starts with 'test_$BROWSER_gdoc_'
- [x] ./tests/regression/gdoc/test_firefox_gdoc_clean_all.sikuli/test_firefox_gdoc_clean_all.sikuli.py:11: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_create_copypaste_image_1.sikuli/test_firefox_gdoc_create_copypaste_image_1.py:26: trailing whitespace
- [x] ./tests/regression/gdoc/test_firefox_gdoc_create_copypaste_table_1.sikuli/test_firefox_gdoc_create_copypaste_table_1.py:24: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_create_copypaste_txt_1.sikuli/test_firefox_gdoc_create_copypaste_txt_1.py:38: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_create_cursormove_50.sikuli/test_firefox_gdoc_create_cursormove_50.py:33: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_delete_basic_image_1.sikuli/test_firefox_gdoc_delete_basic_image_1.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_delete_basic_table_1.sikuli/test_firefox_gdoc_delete_basic_table_1.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_delete_basic_txt_1.sikuli/test_firefox_gdoc_delete_basic_txt_1.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:19: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:20: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:21: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:22: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:23: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:24: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:25: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:26: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:27: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:28: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:30: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:31: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:32: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:33: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:34: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:35: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:36: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:37: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:39: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:40: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:41: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:42: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:43: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:44: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:45: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:46: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:47: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:48: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:50: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:51: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:52: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:53: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:54: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:55: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:56: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:65: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_format10.sikuli/test_firefox_gdoc_format10.py:66: tab on line
- [x] ./tests/regression/gdoc/test_firefox_gdoc_read_basic_image_1.sikuli/test_firefox_gdoc_read_basic_image_1.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_read_basic_table_1.sikuli/test_firefox_gdoc_read_basic_table_1.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_read_basic_table_1_sampleobj.sikuli/test_firefox_gdoc_read_basic_table_1_sampleobj.py:17: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_read_cursormove_3.sikuli/test_firefox_gdoc_read_cursormove_3.py:18: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_gdoc_update_replace_3.sikuli/test_firefox_gdoc_update_replace_3.py:23: trailing whitespace
- [x] ./tests/regression/gdoc/test_firefox_gdoc_update_undoredo_100.sikuli/test_firefox_gdoc_update_undoredo_100.py:25: no newline at EOF
- [x] ./tests/regression/gdoc/test_firefox_load_file.sikuli/test_firefox_load_file.py:0: the file name should starts with 'test_$BROWSER_gdoc_'
- [x] ./tests/test_chrome_switchcontentwindow.sikuli/test_chrome_switchcontentwindow.py:12: no newline at EOF
- [x] ./tests/test_firefox_switchcontentwindow.sikuli/test_firefox_switchcontentwindow.py:12: no newline at EOF
- [x] ./tools/get_metric.py:58: no newline at EOF
- [x] ./tools/parse_hasal_result.py:177: no newline at EOF

**Comment by askeing** [comment]
@ShakoHo @MikeLien @ypwalter ping
XDD

**Comment by MikeLien** [comment]
#221

**Comment by askeing** [comment]
fixed #213 , too
