### ISSUE TITLE
Refactoring Windows 7 and 10 bootstrap

### ISSUE THREAD

**Issue by askeing** [Mozilla-TWQA/Hasal#633]
This is note issue for `bootstrap.bat` refactoring

- [x] Win7 FFmpeg: Check the binary before download and install. [Code Ref](https://github.com/Mozilla-TWQA/Hasal/blob/dev/bootstrap.bat#L163-L178) (@askeing #636) 
- [x] Win10 PATH overcoming the 1024 character limit (@ypwalter #641 #633)
- [x] Win7 PATH overcoming the 1024 character limit (@ypwalter #740)
- [x] Win7 Win10: Check OBS before install it (@askeing #652)
- [ ] Win7 handling of dup in PATH
