### ISSUE TITLE
[Meta] Input latency measurement - Facebook

### ISSUE THREAD

**Issue by bobbyc** [Mozilla-TWQA/Hasal#644]
Measurements:
- [x] FB:  Typing in comments box 
- [x] FB:  Typing in chat box of Facebook Messenger 
- [x] FB:  Typing in status composer box 
- [x] FB:  Single mouse scroll in News Feed 
- [x] FB:  Click on right-arrow in photo viewer 
- [x] FB:  Click on chat emoji to bring chat dialog 
- [x] FB:  Click to open chat table at right-side friend name list box 
- [x] FB:  Click ‘x’ to close chat tab 
- [ ] FB: Typing 100 characters  in comments box (Elapsed time)
- [ ] FB: Typing 100 characters in chat box in Facebook Messenger (Elapsed time)
- [x] FB: Typing 100 characters in status composer box (Elapsed time) #653

**Comment by bobbyc** [comment]
@digitarald Add sub-issue #653 to track discussion.

**Comment by bobbyc** [comment]
Measurement reports: https://github.com/Mozilla-TWQA/Hasal-result/tree/master/20170504/facebook

**Comment by bobbyc** [comment]
Done.
